CREATE TABLE form_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    banner_url VARCHAR(255),
    video_url VARCHAR(255),
    questions_json TEXT,
    theme_mode VARCHAR(255),
    layout_density VARCHAR(255),
    submission_mode VARCHAR(255),
    total_pages INTEGER
);

CREATE TABLE collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT,
    email VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE transfer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT,
    from_email VARCHAR(255),
    to_email VARCHAR(255),
    proposed_new_role VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT,
    form_title VARCHAR(255),
    form_description TEXT,
    full_name VARCHAR(255),
    email VARCHAR(255),
    company VARCHAR(255),
    rating INTEGER,
    submission_mode VARCHAR(255),
    theme_mode VARCHAR(255),
    layout_density VARCHAR(255),
    interests_json TEXT,
    questions_json TEXT,
    answers_json TEXT,
    message TEXT,
    created_at TIMESTAMP
);
