CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT,
    question_id VARCHAR(255),
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255),
    size BIGINT,
    cloudinary_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
